export const ROUTES = {
    HOME:"/perfume",
    REGISTRATION:"/registration",
    BASKET:"/basket",
    BONUSES:"/bonuses",
    DOCUMENTATION:"/documentation",
    ABOUTUS:"/aboutUs",
    MANCATALOGPAGE:"/manCatalogPage/",
    WOMENCATALOGPAGE:"/womenCatalogPage/",
    UNISEX:"/unisexCatalogPage/",
    SINGLEPRODUCT:"/singleProduct/",
    USERPAGE:"/userPage/",
    BONUSESPANEL:"/bonusesPanel/",
    ORDERPANEL:"/orderPanel/",
    DOWNLOADSPANEL:"/downloadsPanel/",
    LOCATIONPANEL:"/locationPanel/",
    USERPANEL:"/userPanel/",
    NOTFOUNDPAGE:"/*"
};